/**
 * Author:  pi
 * Created: Jul 4, 2021
 */

---
create table IF NOT EXISTS BUG_CONFIG_ENTITY (
    ID bigint generated by default as identity, 
    VERSION bigint not null, 
    CREATED_WHEN timestamp, 

    CONFIG_DESCRIPTION varchar(2048), 
    CONFIG_KEY varchar(256) not null, 
    UPDATED_WHEN timestamp, 
    CONFIG_VALUE varchar(255), 
    primary key (ID)
);

alter table BUG_CONFIG_ENTITY add constraint UK_CONFIG_KEY unique (CONFIG_KEY);
