/**
 * Author:  pi
 * Created: Jul 4, 2021
 */

--- init script

create table EVENT_ENTITY (
    ID bigint generated by default as identity, 
    CREATED_BY varchar(255), 
    CREATED_WHEN timestamp, 
    UPDATED_BY varchar(255), 
    UPDATED_WHEN timestamp, 
    VERSION bigint not null, 

    BOOKING_STATUS varchar(20), 
    CODE varchar(128) not null, 
    DESCRIPTION varchar(1024), 
    COMMUNE varchar(256), 
    DATETIME_END timestamp, 
    DATETIME_FULL_DAY boolean, 
    DATETIME_START timestamp, 
    DATETIME_SERIE boolean, 
    LOCATION varchar(256), 
    ORGANIZER varchar(256), 
    NAME varchar(256) not null, 
    primary key (ID)
);
